language: go

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install pygments --user
  - pip install pygments-github-lexers --user
  - go get -u -v github.com/spf13/hugo

script:
  - git clone https://github.com/phil-opp/blog_os.git
  - cp -r blog_os/blog ../blog
  - hugo

after_success: bash travis-blog-update.sh
