language: go

go:
  - 1.6

install:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install pygments --user
  - pip install pygments-github-lexers --user
  #- go get -u -v github.com/spf13/hugo
  - wget https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16_linux-64bit.tgz
  - tar xf hugo_0.16_linux-64bit.tgz

script:
  - git clone https://github.com/phil-opp/blog_os.git
  - cp -r blog_os/blog ../blog
  - ./hugo

after_success: bash ci/travis-blog-update.sh

notifications:
  email:
    on_success: never
