# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               phil-opp's blog
full_title:          Writing an OS in Rust
tagline:             Philipp Oppermann's blog
baseurl:             ""
url:                 http://os.phil-opp.com

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "superscript", "footnotes"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Philipp Oppermann
  email:             contact@phil-opp.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/phil-opp/blog_os

# Navigation
navigation_pages:
  RSS: '/atom.xml'
  Archive: '/archive.html'

contact: '/contact.html'

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

enable_disqus: true
enable_analytics: true
