title = "Writing an OS in Rust"
base_url = "https://os.phil-opp.com"

highlight_code = true
highlight_theme = "monokai"
generate_rss = true

[extra]
subtitle = "Philipp Oppermann's blog"
author = { name = "Philipp Oppermann" }
