title = "Writing an OS in Rust"
base_url = "https://os.phil-opp.com"
description = "This blog series creates a small operating system in the Rust programming language. Each post is a small tutorial and includes all needed code."

highlight_code = true
highlight_theme = "visual-studio-dark"
generate_rss = true

languages = [
    { code = "zh-CN" }, # Chinese (simplified)
    { code = "zh-TW" }, # Chinese (tradictional)
    { code = "ja" }, # Japanese
]

ignored_content = ["*/README.md"]

[link_checker]
skip_prefixes = [
    "https://crates.io/crates", # see https://github.com/rust-lang/crates.io/issues/788
    "https://www.amd.com/system/files/TechDocs/", # seems to have problems with PDFs
    "https://developer.apple.com/library/archive/qa/qa1118/_index.html", # results in a 401 (I don't know why)
    "https://github.com", # rate limiting often leads to "Error 429 Too Many Requests"
    "https://www.linkedin.com/", # seems to send invalid HTTP status codes
]
skip_anchor_prefixes = [
     "https://github.com/", # see https://github.com/getzola/zola/issues/805
     "https://docs.rs/x86_64/0.1.2/src/", # source code highlight
     "https://www.math.utah.edu/docs/info/ld_3.html", # see https://github.com/getzola/zola/issues/948
     "https://web.stanford.edu/class/cs140/projects/pintos/specs/freevga/vga/vgamem.htm", # see https://github.com/getzola/zola/issues/948
]

[extra]
subtitle = "Philipp Oppermann's blog"
author = { name = "Philipp Oppermann" }
