title = "Writing an OS in Rust"
base_url = "https://os.phil-opp.com"

highlight_code = true
highlight_theme = "visual-studio-dark"
generate_rss = true

languages = [
    { code = "zh-CN" }, # Chinese (simplified)
]

[extra]
subtitle = "Philipp Oppermann's blog"
author = { name = "Philipp Oppermann" }
